<template>
  <main class="map-page"><InspirationShell/><section class="map-layout">
    <aside><el-input v-model="query" clearable placeholder="搜索地图中的灵感" :prefix-icon="Search" @input="scheduleLoad"/><div v-if="selected" class="place-panel"><div class="place-title"><MapPin :size="20"/><div><h2>{{ selected.name }}</h2><span>{{ selected.count }} 条灵感</span></div></div><InspirationCard v-for="item in selected.items" :key="item.id" :item="item" /></div><el-empty v-else description="点击地图标记查看地点灵感"/></aside>
    <div class="map-host"><div ref="host" class="map-canvas" aria-label="灵感地图"></div><div v-if="loading" class="map-state">地图加载中…</div><div v-else-if="error" class="map-state">地图加载失败 <el-button @click="initialize">重试</el-button></div></div>
  </section></main>
</template>
<script setup>
import { onBeforeUnmount,onMounted,ref } from 'vue';import { Search,MapPin } from 'lucide-vue-next';import { getInspirationMap,getInspirations } from '../api/inspiration';import InspirationShell from '../components/inspiration/InspirationShell.vue';import InspirationCard from '../components/inspiration/InspirationCard.vue';const host=ref(null),loading=ref(true),error=ref(false),query=ref(''),selected=ref(null);let map,maplibregl,markers=[],timer
const clearMarkers=()=>{markers.forEach(m=>m.remove());markers=[]};const createMarker=point=>{const el=document.createElement('button'),earliest=point.preview?.[0],cover=earliest?.cover_url||'';el.className='inspiration-marker';el.type='button';el.setAttribute('aria-label',`${point.name}，显示最早创建的灵感${earliest?`“${earliest.title}”`:''}，共${point.count}条`);const placeholder=document.createElement('span');placeholder.className='inspiration-marker-placeholder';placeholder.textContent=earliest?.title?.trim().slice(0,1)||'灵';el.appendChild(placeholder);if(cover){const image=document.createElement('img');image.className='inspiration-marker-cover';image.src=cover;image.alt='';image.addEventListener('error',()=>image.remove(),{once:true});el.appendChild(image)}if(point.count>1){const badge=document.createElement('span');badge.className='inspiration-marker-count';badge.textContent=`+${point.count-1}`;el.appendChild(badge)}el.addEventListener('click',()=>selectPoint(point));return el};const loadPoints=async()=>{try{const {data}=await getInspirationMap({query:query.value||undefined});clearMarkers();data.points.forEach(point=>{markers.push(new maplibregl.Marker({element:createMarker(point)}).setLngLat([point.longitude,point.latitude]).addTo(map))});if(data.points.length&&!selected.value){const bounds=new maplibregl.LngLatBounds();data.points.forEach(p=>bounds.extend([p.longitude,p.latitude]));map.fitBounds(bounds,{padding:80,maxZoom:13})}}catch{error.value=true}}
const selectPoint=async point=>{selected.value={...point,items:[]};try{const {data}=await getInspirations({query:point.name,limit:100});selected.value.items=data.filter(i=>i.place_id===point.key.replace('place:','')||(!i.place_id&&Math.abs(Number(i.latitude)-point.latitude)<.00002&&Math.abs(Number(i.longitude)-point.longitude)<.00002))}catch{selected.value.items=point.preview}};const initialize=async()=>{if(map||!host.value)return;loading.value=true;error.value=false;try{const module=await import('maplibre-gl');await import('maplibre-gl/dist/maplibre-gl.css');maplibregl=module.default;map=new maplibregl.Map({container:host.value,center:[114.1694,22.3193],zoom:10,style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]}});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');map.on('load',async()=>{loading.value=false;await loadPoints()});map.on('error',()=>{if(!map.loaded())error.value=true;loading.value=false})}catch{loading.value=false;error.value=true}};const scheduleLoad=()=>{clearTimeout(timer);timer=setTimeout(loadPoints,300)};onMounted(initialize);onBeforeUnmount(()=>{clearTimeout(timer);clearMarkers();map?.remove()})
</script>
<style scoped>.map-page{padding:0 var(--content-gutter) 32px}.map-layout{display:grid;grid-template-columns:360px minmax(0,1fr);height:calc(100dvh - var(--header-height) - 190px);min-height:560px;margin-top:20px;border:var(--border-default);background:var(--color-paper-light)}aside{overflow-y:auto;padding:16px;border-right:var(--border-default)}.place-panel{display:grid;gap:14px;margin-top:18px}.place-title{display:flex;gap:10px;align-items:center}.place-title h2,.place-title span{margin:0}.place-title span{color:var(--color-ink-secondary);font-size:var(--text-sm)}.map-host{position:relative;min-width:0}.map-canvas{width:100%;height:100%}.map-state{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;gap:10px;background:var(--color-paper)}:global(.inspiration-marker){position:relative;width:64px;height:64px;overflow:visible;padding:0;border:3px solid var(--color-paper-light);border-radius:15px;background:var(--color-brand-soft);box-shadow:0 3px 12px rgba(0,0,0,.22);color:var(--color-brand);font-size:18px;font-weight:800;cursor:pointer}:global(.inspiration-marker-placeholder){display:grid;width:100%;height:100%;place-items:center;overflow:hidden;border-radius:12px}:global(.inspiration-marker-cover){position:absolute;inset:0;width:100%;height:100%;border-radius:12px;object-fit:cover}:global(.inspiration-marker-count){position:absolute;z-index:2;top:-10px;right:-12px;display:grid;min-width:29px;height:29px;place-items:center;padding:0 6px;border:2px solid var(--color-paper-light);border-radius:999px;background:var(--color-brand);box-shadow:0 2px 6px rgba(0,0,0,.18);color:#fff;font-size:11px;font-weight:800;line-height:1}@media(max-width:760px){.map-layout{grid-template-columns:1fr;height:auto}.map-host{height:55dvh;min-height:420px;grid-row:1}aside{border-right:0;border-top:var(--border-default);max-height:none}}</style>
