<template>
  <main class="detail-page" v-loading="loading">
    <div v-if="item" class="detail-wrap">
      <header class="detail-actions"><button type="button" @click="router.back()"><ArrowLeft :size="20"/>返回</button><div><router-link :to="`/inspirations/${item.id}/edit`"><el-button><Pencil :size="17"/>编辑</el-button></router-link><el-button type="danger" plain @click="remove"><Trash2 :size="17"/>归档</el-button></div></header>
      <article>
        <div class="kicker"><span>{{ item.status==='draft'?'草稿':'已保存' }}</span><time>更新于 {{ formatDate(item.updated_at) }}</time></div>
        <h1>{{ item.title }}</h1><p v-if="item.summary" class="summary">{{ item.summary }}</p>
        <div v-if="item.tags?.length" class="tags"><span v-for="tag in item.tags" :key="tag">{{ tag }}</span></div>
        <section class="content"><template v-for="(block,index) in item.content" :key="index"><img v-if="block.type==='image'" :src="block.url" :alt="block.alt||item.title" loading="lazy"/><blockquote v-else-if="block.type==='quote'">{{ block.text }}</blockquote><h2 v-else-if="block.type==='heading'">{{ block.text }}</h2><p v-else>{{ block.text }}</p></template></section>
        <section v-if="item.latitude!=null" class="place"><div><MapPin :size="22"/><div><h2>{{ item.location_name||'拍摄地点' }}</h2><p>{{ item.location_address }}</p></div></div><div class="map"><LocationMap :latitude="Number(item.latitude)" :longitude="Number(item.longitude)" :zoom="14" /></div></section>
      </article>
    </div>
    <el-result v-else-if="!loading" icon="error" title="找不到这条灵感"><template #extra><router-link to="/inspirations"><el-button>返回仓库</el-button></router-link></template></el-result>
  </main>
</template>
<script setup>
import { onMounted,ref } from 'vue';import { useRoute,useRouter } from 'vue-router';import { ElMessage,ElMessageBox } from 'element-plus';import { ArrowLeft,MapPin,Pencil,Trash2 } from 'lucide-vue-next';import { deleteInspiration,getInspiration } from '../api/inspiration';import LocationMap from '../components/location/LocationMap.vue';const route=useRoute(),router=useRouter(),item=ref(null),loading=ref(true);const formatDate=v=>new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));const load=async()=>{try{item.value=(await getInspiration(route.params.inspirationId)).data}catch{}finally{loading.value=false}};const remove=async()=>{try{await ElMessageBox.confirm('归档后将不会出现在仓库和地图中。','归档灵感',{type:'warning',confirmButtonText:'确认归档'});await deleteInspiration(item.value.id);ElMessage.success('已归档');router.replace('/inspirations')}catch{}};onMounted(load)
</script>
<style scoped>.detail-page{padding:0 var(--content-gutter) 80px}.detail-wrap{max-width:920px;margin:auto}.detail-actions{display:flex;justify-content:space-between;align-items:center;min-height:72px;border-bottom:var(--border-default)}.detail-actions button{display:inline-flex;align-items:center;gap:7px;min-height:44px}.detail-actions>button{border:0;background:none;cursor:pointer}.detail-actions>div{display:flex;gap:8px}article{max-width:760px;margin:56px auto}.kicker{display:flex;justify-content:space-between;color:var(--color-ink-tertiary);font-size:var(--text-sm)}.kicker span{color:var(--color-brand);font-weight:700}h1{font-size:clamp(34px,6vw,58px);line-height:1.15;margin:14px 0}.summary{font-size:var(--text-xl);color:var(--color-ink-secondary)}.tags{display:flex;flex-wrap:wrap;gap:8px;margin:22px 0}.tags span{padding:5px 10px;background:var(--color-brand-light);color:var(--color-brand)}.content{display:grid;gap:22px;margin-top:42px}.content p,.content blockquote{margin:0;font-size:18px;line-height:1.9}.content img{width:100%;max-height:760px;object-fit:contain;background:var(--color-paper-light)}blockquote{padding:18px 24px;border-left:3px solid var(--color-brand);background:var(--color-brand-light)}.place{margin-top:56px;padding-top:28px;border-top:var(--border-default)}.place>div:first-child{display:flex;gap:12px;align-items:flex-start}.place h2,.place p{margin:0}.place p{color:var(--color-ink-secondary)}.map{height:320px;margin-top:18px;border:var(--border-default)}@media(max-width:600px){article{margin-top:34px}.detail-actions>div .el-button{padding:0 10px}}</style>
