<template>
  <main class="editor-page">
    <header><button type="button" class="back" @click="leave"><ArrowLeft :size="20"/>返回</button><div class="save-state" aria-live="polite">{{ saveState }}</div><div class="actions"><el-button :loading="saving" @click="save('draft')">保存草稿</el-button><el-button type="primary" :loading="saving" @click="save('saved')">保存灵感</el-button></div></header>
    <form class="editor" @submit.prevent="save('saved')">
      <label>标题 <span>*</span><el-input v-model="form.title" maxlength="120" show-word-limit placeholder="给这条灵感一个名字" size="large" @input="markDirty"/></label>
      <label>摘要<el-input v-model="form.summary" maxlength="300" show-word-limit type="textarea" :rows="3" placeholder="用一两句话记住它最重要的感觉" @input="markDirty"/></label>
      <fieldset><legend>灵感内容</legend><div v-for="(block,index) in form.content" :key="index" class="block">
        <img v-if="block.type==='image'" :src="block.thumb_url||block.url" :alt="block.alt||'灵感图片'" />
        <el-input v-else v-model="block.text" type="textarea" :rows="4" placeholder="写下光线、构图、情绪或拍摄想法……" @input="markDirty"/>
        <button type="button" aria-label="删除内容块" @click="removeBlock(index)"><Trash2 :size="18"/></button>
      </div><div class="block-actions"><el-button @click="addParagraph"><AlignLeft :size="17"/>添加段落</el-button><el-upload :show-file-list="false" :http-request="uploadImage" accept="image/jpeg,image/png,image/webp"><el-button :loading="uploading"><ImagePlus :size="17"/>添加图片</el-button></el-upload></div></fieldset>
      <label>标签 <small>最多 10 个</small><TagInput v-model="form.tags" placeholder="输入标签后按回车" @update:model-value="markDirty"/></label>
      <fieldset><legend>地点</legend><div v-if="form.location_name" class="location"><MapPin :size="20"/><div><strong>{{ form.location_name }}</strong><span>{{ form.location_address }}</span></div><button type="button" aria-label="移除地点" @click="clearLocation"><X :size="18"/></button></div><el-button v-else @click="pickerVisible=true"><MapPin :size="17"/>关联拍摄地点</el-button></fieldset>
    </form>
    <LocationPickerDialog v-model="pickerVisible" :location="locationValue" @confirm="setLocation" />
  </main>
</template>
<script setup>
import { computed,onBeforeUnmount,onMounted,reactive,ref } from 'vue';import { useRoute,useRouter } from 'vue-router';import { ElMessage,ElMessageBox } from 'element-plus';import { AlignLeft,ArrowLeft,ImagePlus,MapPin,Trash2,X } from 'lucide-vue-next';import { createInspiration,getInspiration,updateInspiration,uploadInspirationImage } from '../api/inspiration';import TagInput from '../components/TagInput.vue';import LocationPickerDialog from '../components/location/LocationPickerDialog.vue'
const route=useRoute(),router=useRouter(),saving=ref(false),uploading=ref(false),dirty=ref(false),saveState=ref('尚未保存'),pickerVisible=ref(false);const form=reactive({title:'',summary:'',content:[{type:'paragraph',text:''}],cover_url:null,tags:[],status:'draft',location_name:null,location_address:null,latitude:null,longitude:null,place_id:null,provider:null,coordinate_system:null,location_precision:null});const isEdit=computed(()=>Boolean(route.params.inspirationId));const locationValue=computed(()=>({name:form.location_name,address:form.location_address,latitude:form.latitude,longitude:form.longitude,place_id:form.place_id}));let autosaveTimer
const markDirty=()=>{dirty.value=true;saveState.value='有未保存修改';clearTimeout(autosaveTimer);if(isEdit.value&&form.title.trim())autosaveTimer=setTimeout(()=>save(form.status==='saved'?'saved':'draft',true),1200)}
const payload=status=>({...form,title:form.title.trim(),content:form.content.filter(b=>b.type==='image'||b.text?.trim()),status})
const save=async(status='draft',silent=false)=>{if(!form.title.trim()){if(!silent)ElMessage.warning('请先填写标题');return}saving.value=true;saveState.value='保存中…';try{const res=isEdit.value?await updateInspiration(route.params.inspirationId,payload(status)):await createInspiration(payload(status));form.status=res.data.status;dirty.value=false;saveState.value='已保存';if(!isEdit.value)await router.replace(`/inspirations/${res.data.id}/edit`);if(!silent&&status==='saved'){ElMessage.success('灵感已保存');router.push(`/inspirations/${res.data.id}`)}}catch{saveState.value='保存失败，可重试';if(!silent)ElMessage.error('保存失败，请稍后重试')}finally{saving.value=false}}
const load=async()=>{if(!isEdit.value)return;try{Object.assign(form,(await getInspiration(route.params.inspirationId)).data);if(!form.content.length)form.content=[{type:'paragraph',text:''}];saveState.value='已保存'}catch{ElMessage.error('无法加载灵感');router.replace('/inspirations')}}
const addParagraph=()=>{form.content.push({type:'paragraph',text:''});markDirty()};const removeBlock=i=>{form.content.splice(i,1);markDirty()};const uploadImage=async({file})=>{uploading.value=true;try{const {data}=await uploadInspirationImage(file);form.content.push({type:'image',url:data.url,thumb_url:data.thumb_url,alt:form.title});if(!form.cover_url)form.cover_url=data.thumb_url||data.url;markDirty()}catch{ElMessage.error('图片上传失败')}finally{uploading.value=false}}
const setLocation=value=>{Object.assign(form,{location_name:value.name,location_address:value.address,latitude:value.latitude,longitude:value.longitude,place_id:value.place_id,provider:value.provider,coordinate_system:value.coordinate_system,location_precision:value.precision});markDirty()};const clearLocation=()=>{Object.assign(form,{location_name:null,location_address:null,latitude:null,longitude:null,place_id:null,provider:null,coordinate_system:null,location_precision:null});markDirty()}
const leave=async()=>{if(dirty.value){try{await ElMessageBox.confirm('当前修改尚未保存，确定离开吗？','未保存的修改',{confirmButtonText:'放弃离开',cancelButtonText:'继续编辑',type:'warning'})}catch{return}}router.push('/inspirations')};const beforeUnload=e=>{if(dirty.value){e.preventDefault();e.returnValue=''}};onMounted(()=>{load();window.addEventListener('beforeunload',beforeUnload)});onBeforeUnmount(()=>{clearTimeout(autosaveTimer);window.removeEventListener('beforeunload',beforeUnload)})
</script>
<style scoped>.editor-page{max-width:980px!important;padding:0 var(--content-gutter) 72px}.editor-page>header{position:sticky;top:var(--header-height);z-index:10;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;min-height:72px;background:rgba(250,247,242,.96);border-bottom:var(--border-default)}.back{display:flex;align-items:center;gap:7px;width:max-content;min-height:44px;border:0;background:none;cursor:pointer}.actions{display:flex;justify-content:flex-end;gap:8px}.save-state{color:var(--color-ink-secondary);font-size:var(--text-sm)}.editor{display:grid;gap:28px;margin:36px auto 0;max-width:760px}.editor label{display:grid;gap:9px;font-weight:700}.editor label span{color:var(--color-danger)}.editor small{color:var(--color-ink-secondary);font-weight:400}fieldset{display:grid;gap:12px;margin:0;padding:20px;border:var(--border-default);background:var(--color-paper-light)}legend{padding:0 8px;font-weight:700}.block{position:relative}.block img{width:100%;max-height:520px;object-fit:contain;background:var(--color-paper)}.block>button,.location>button{position:absolute;top:8px;right:8px;width:44px;height:44px;display:grid;place-items:center;border:var(--border-default);background:var(--color-paper-light);cursor:pointer}.block-actions{display:flex;gap:8px}.location{position:relative;display:flex;align-items:flex-start;gap:12px;padding:14px 58px 14px 14px;background:var(--color-brand-light)}.location div{display:grid}.location span{color:var(--color-ink-secondary);font-size:var(--text-sm)}@media(max-width:620px){.editor-page>header{grid-template-columns:auto 1fr}.save-state{display:none}.actions{grid-column:1/-1;padding-bottom:10px}.actions>*{flex:1}.editor{margin-top:24px}.block-actions{flex-direction:column}}</style>
